server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:mem:notifydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  redis:
    data:
      host: localhost
      port: 6379
      timeout: 60000
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

notifycentral:
  notification-type: kafka
  retry:
    max-attempts: 3
    initial-backoff-ms: 200
  executor:
    core-pool-size: 4
    max-pool-size: 8
    queue-capacity: 100
  kafka:
    host: localhost
    port: 9092
